version: 0.0
os: windows
files:
  - source: index.html
    destination: C:\website-data
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: .\RemoveApp.ps1
      timeout: 30
  ApplicationStart:
    - location: .\InstallApp.ps1
      timeout: 300
